version: "3.3"
services:
  memcached:
    image: memcached:1.6.18
    ports:
      - "11211:11211"
  grpcservice:
    build:
      dockerfile: Dockerfile
    ports:
      - "5300:5300"
      - "8080:8080"
      - "8888:8888"
    depends_on:
      - memcached
    environment:
      MEMCACHED_ADDR: "memcached:11211"
