version: "3.3"
services:
  memcached:
    image: memcached:1.6.18
    ports:
      - "11211:11211"
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh scylla 9042 -e 'select * from system.scylla_local;'"]
      interval: 30s
      timeout: 3s
      retries: 3
  migrations:
    build:
      dockerfile: migrations/Dockerfile
    depends_on:
      scylla:
        condition: service_healthy
    environment:
      SCYLLA_DB: "scylla:9042"
  grpcservice:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8888:8888"
    depends_on:
      - memcached
      - migrations
    environment:
      MEMCACHE_GRPC_PORT: ":8081"
      INTERNAL_STORAGE_GRPC_PORT: ":8080"
      SCYLLA_GRPC_PORT: ":8082"
      MEMCACHED_ADDR: "memcached:11211"
      SCYLLA_DB: "scylla:9042"